---

- name: Ensure supervisor is installed
  apt: name=supervisor state=present
  remote_user: root

- name: Create the supervisor config file
  template: src=program.j2
            dest=/etc/supervisor/conf.d/uwsgi_{{ prefix }}.conf
            owner=root
            group=root
            mode=0644
  remote_user: root
  notify:
    - reread uwsgi config
    - restart uwsgi

- name: Copy the uwsgi.ini file
  template: src=uwsgi.ini.j2
            dest={{ project_home }}src/{{ project_name }}/conf/uwsgi.ini
            owner={{ application_user }}
            group={{ application_user }}
            mode=0600
  notify:
    - restart uwsgi

- name: Ensure the log dir exists
  file: name="{{ project_home }}/log" state=directory

- name: Ensure the supervisor config file is loaded
  supervisorctl: name=uwsgi_{{ prefix }} state=present
  remote_user: root
  notify:
    - restart uwsgi
