# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_overviewpagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overviewpagelink',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
    ]
