# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('albums', '0004_auto_20160424_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewpage',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='Main image for this page. The body will be overlaid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
