---

- name: Ensure environment file directory exists
  file: name={{ env_dir }} state=directory mode=0700 owner={{ application_user }}

- name: Copy the environment variables file
  template: src="env.txt.j2"
            dest={{ env_file_dest }}
            owner={{ application_user }}
            group={{ application_user }}
            mode=0700
